version: '3.1'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    networks:
      - portainer
      # - nginx
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/portainer/config:/data

networks:
  portainer:
    name: portainer
  nginx:
    external: true
