version: '3.1'
services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8090:8080
